name: Publish Docker Image

on: push

env:
  AWS_REGION: us-west-1

permissions:
  id-token: write
  contents: read

jobs:
  BuildAndPublishImage:
    runs-on: ubuntu-latest
    - name: Clone Repo
      uses: actions/checkout@v3
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::661723793673:role/github-action-admin
          role-session-name: githubactionssession
          aws-region: ${{ env.AWS_REGION }}